version: '3.8'

services:
  db:
    image: postgres:15
    container_name: ledger_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: personal-fin-ledger
    ports:
      - "5433:5432" # Maps port 5433 on your local machine to 5432 in the container
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ledger_backend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=personal-fin-ledger
    depends_on:
      - db

volumes:
  pgdata:
